spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/operator_bot
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
  token: "7921796282:AAFvLj5bF0znjjvjXs7oxKQq-XMoINt0Uw8"
  username: "@zeroonetaskbot"
  file-api: "https://api.telegram.org/file/bot7668006662:AAFGspD8yJTB5njgXCjSYAmBQZvdDnaBss8/"


