spring:
  application:
    name: order-app
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

