spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

