package com.bbhgroup.zeroone_task

enum class Role {
    USER, ADMIN, OPERATOR
}

enum class Languages(val key: String) {
    UZ("uz"),
    RU("ru"),
    EN("en")
}

enum class SessionStatus {
    PENDING,
    PROCESSING,
    COMPLETED
}

enum class ErrorCodes(val code: Int) {


    INVALID_MESSAGE_TEXT(1),
    INVALID_FILE_ID(2),
    SESSION_NOT_FOUND_M(3),
    INVALID_SESSION_STATUS_M(4),
    MESSAGE_NOT_FOUND(5),
    PROHIBITED_UPDATE_MESSAGE(6),
    INVALID_SESSION_CLIENT_ID(7),


    EMPTY_QUEUE_CLIENT_ID(30),
    EMPTY_LIST_M(31),
    QUE_NOT_FOUND(32),
    QUE_OWNER_EXCEPTION(33),
    INVALID_MESSAGE_TYPE(34),
    USER_NOT_FOUND(100),
    USER_ALREADY_EXISTS(101),
    USER_BAD_REQUEST(102),
    DATA_HAS_ALREADY_EXISTS(103),

    OPERATOR_NOT_FOUND(200),
    SESSION_NOT_FOUND(201),
    RATING_NOT_FOUND(300),
    RATING_ALREADY_EXISTS(301)

}

enum class BotSteps{
    START,
    SELECT_LANGUAGE,
    SHARE_CONTACT,
    CONNECT_OPERATOR,
    SENDING_MESSAGES,
    END_CHAT
}
enum class MessageKeys{
    SHARE_CONTACT,
    SUCCESS_SHARE_CONTACT,
    ALREADY_REGISTERED,
    CANCEL_CHAT,
    SHARE_OTHER_CONTACT,
    SHARE_CONTACT_BUTTON,
    WRITE_TO_OPERATOR,
    TEXT_CONNECT_BUTTON_TO_OPERATOR,
    CONNECT_BUTTON_TO_OPERATOR,
    START_WORK,
    START_WORK_BUTTON,
    END_WORK,
    END_CHAT,
    NOT_FOUND_PENDING_CLIENT,
    SEND_RATE_VALUE,
    USER_BLOCKED_BOT
}

enum class MessageType{
    TEXT,
    VOICE,
    AUDIO,
    VIDEO,
    STICKER,
    GIF,
    PHOTO,
    VIDEO_NOTE,
    DOCUMENT,
    LOCATION,
    POLL,
    UNKNOWN
}
enum class Status{
    BUSY, FREE, NOT_WORKING
}
enum class UserStatus{
    ACTIVE, BLOCKED
}